export default null

export const MutationEvents = {
  UPDATE_MOCK_DATA: 'MUTATION_EVENT_UPDATE_MOCK_DATA',
  TOGGLE_MOCK_ITEM_STATUS: 'MUTATION_EVENT_TOGGLE_MOCK_ITEM_STATUS',
  CHANGE_SELECTED_URL: 'MUTATION_EVENT_CHANGE_SELECTED_URL',
  CHANGE_SELECTED_METHOD: 'MUTATION_EVENT_CHANGE_SELECTED_METHOD',
  CHANGE_DIALOG_STATUS: 'MUTATION_EVENT_CHANGE_DIALOG_STATUS',
}

export const ActionEvents = {
  TOGGLE_MOCK_ITEM_STATUS: 'ACTION_EVENT_TOGGLE_MOCK_ITEM_STATUS',
  CHANGE_SELECTED_URL: 'ACTION_EVENT_CHANGE_SELECTED_URL',
  RENAME_MOCK_URL: 'ACTION_EVENT_RENAME_MOCK_URL',
  OPEN_DIALOG: 'MUTATION_EVENT_OPEN_DIALOG',
  CLOSE_DIALOG: 'MUTATION_EVENT_CLOSE_DIALOG',
}
